const os = require('os')
console.log('OS:', os.platform())
console.log('CPU arch:', os.arch())
console.log('CPU info:', os.cpus())
console.log('free mem:', os.freemem())
console.log('total mem:', os.totalmem())
console.log('home dir:', os.homedir())